services:
  myfirstapp-web:
    image: nginx:latest
    container_name: myfirstapp-web
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  myfirstapp-app:
    build: ./php
    container_name: myfirstapp-app
    volumes:
      - ../src:/var/www/html

  myfirstapp-db:
    image: mysql:latest
    container_name: myfirstapp-db
    environment:
      MYSQL_DATABASE: "myfirstapp"
      MYSQL_ROOT_PASSWORD: "root"


